[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# Convenience path (optional): /api/submissions → function
[[redirects]]
  from = "/api/submissions"
  to = "/.netlify/functions/submissions"
  status = 200
